spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  main:
    allow-bean-definition-overriding: true

  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: true
    placeholder-replacement: false

server:
  port: 8080

logging:
  level:
    by.bsuir.medical_application.security: DEBUG
    by.bsuir.medical_application.utils: DEBUG
    by.bsuir.medical_application.controller: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: mySuperSecretKeyForJWTGeneration2025
  expiration: 86400000
  refresh-expiration: 86400000

bcrypt:
  strength: 12